# Generated by Django 2.2.4 on 2019-08-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kagi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('key_name', models.CharField(max_length=64)),
                ('public_key', models.TextField(unique=True)),
                ('ukey', models.TextField(unique=True)),
                ('credential_id', models.TextField(unique=True)),
                ('sign_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
