# Generated by Django 2.2.4 on 2019-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kagi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthnkey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
