# Generated by Django 2.2.4 on 2019-08-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kagi', '0002_webauthnkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U2FKey',
        ),
    ]
